### ISSUE TITLE
Re-running benchmarks

### ISSUE THREAD

**Issue by Laurae2** [Laurae2/gbt_benchmarks#2]
@guolinke I am running again the benchmarks. Do you have a specific version/commit you would like me to benchmark?

**Comment by guolinke** [comment]
@Laurae2 I think you can use the latest master code

**Comment by Laurae2** [comment]
@hcho3 Do you have a specific commit from xgboost you would like me to run the benchmarks? I am not counting the time to build the matrix, only the training time. cf dmlc/xgboost#2326 - in addition, only the first to the last iteration will count.

I'll use by default dmlc/xgboost#2501.

@guolinke I can try to benchmark MinGW + Visual Studio LightGBM if you want.

**Comment by Laurae2** [comment]
Preliminary results are below:

[benchmark_lot.zip](https://github.com/Laurae2/gbt_benchmarks/files/1190091/benchmark_lot.zip)

(Bosch + Higgs on LightGBM Visual Studio + xgboost depthwise + xgboost lossguide + xgboost exact)
